### ISSUE TITLE
ffmpeg4.2  Android arm64-v8a 版本无法加载libswscale 报错：invalid ELF file

### ISSUE THREAD

**Issue by lvzhaobing** [wang-bin/avbuild#45]
参考：https://stackoverflow.com/questions/60850313/invalid-elf-file
我遇到了和如上链接相同的错误：
我按照WIKI上Android的编译步骤，成功编译出了arm64-v8a 和 armeabi-v7a版本的 QtAV so库
其中 armeabi-v7a 能够正常加载并且运行一切正常
后来我需要把编译的目标 ABI 切换到 arm64-v8a 发现这个错误，起初怀疑是下载的so库有问题，后来重新下载了ffmpeg4.2的两个目前最新的版本：ffmpeg-4.2-android.tar.xz 和 ffmpeg-4.2-android-lite.tar.xz
报错都是和上边一样的，怀疑是libswscale这个库arm64编译出的文件或编译配置有问题？求助如何能够解决此问题。
java.lang.UnsatisfiedLinkError: dlopen failed: invalid ELF file “/data/app/xxxx.xxxx/lib/arm64/libswscale.so” load segment[4]: p_offset (0x6f000) + p_filesz (0x0) ( = 0x6f000) past end of file (0x6e910)
at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1633)
        at org.qtproject.qt5.android.QtNative$2.run(QtNative.java:199)
        at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
        at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
        at java.lang.Thread.run(Thread.java:764)

**Comment by wang-bin** [comment]
ndk或ffmpeg问题，之前已经解决 https://github.com/wang-bin/avbuild/issues/41
最新的ffmpeg-4.2-android-lite.tar.xz和其他几个包经验证也没发现这个问题。
